### PR TITLE
Ucca1.3.5

### PR DESCRIPTION
**Pull request by lovodkin93**
updated the test_validation.py and the vallidation.py files.
Please don't merge the test_evaluation.py file.

### CODE REVIEW

**Review by danielhers — CHANGES_REQUESTED** [review]
Thanks! Looks like some tests fail, though. Would you take a look please? https://travis-ci.com/github/danielhers/ucca/jobs/396914190#L663

**Comment by lovodkin93** [comment]
updated the code.
Pay attention that there are still going to be two errors - but those errors are correct as the first one (discontiguous-True) generates a UCCA graph where a D unit has a G child and also C and E units are siblings with G unit (which is also illegal), which is illegal, and the second error (l1_passage-True) generates a UCCA graph where a H unit has H and L children, which is also illegal

**Review by danielhers — CHANGES_REQUESTED** [review]
Thanks! Any chance you could fix the failing graphs to be valid, please? :)

**Comment by lovodkin93** [comment]
Updated the discontiguous and the l1_passage tests in test_validation.py (and all the relevant assertions)

**Comment by danielhers** [comment]
Great! There seem to be conflicts now though... do you understand why?

**Comment by lovodkin93** [comment]
> Great! There seem to be conflicts now though... do you understand why?

it seems to be caused by the 'main_rel' parameter that is being checked in the ucca/tests/test_constructions.py file. In the version I cloned of UCCA, this parameter wasn't included. For now I will add it to the changes I've made. Please let me know if there are any problems.

**Comment by lovodkin93** [comment]
resolved the conflicts.

**Comment by danielhers** [comment]
Thanks again, but now the tests fail again... because you changed the path to the XML file to include `../../`. I think the test code assumes you run it from the project root as `pytest .` or `pytest ucca/tests` and not from inside the `ucca/tests` directory.

**Comment by lovodkin93** [comment]
Hey, you are right. On my computer it works only with "../../", and I forgot to get rid of it before committing. Now it should be okay. Unless the "main_rel" causes problems.

**Review by danielhers — APPROVED** [review]

**Pull request merged**
